###
POST http://localhost:3001/groups/create
Content-Type: application/json

{
  "name": "One piece fans",
  "ownerId": 16,
  "group_description": "i love one piece"
}

###
POST http://localhost:3001/groups/addMember
Content-Type: application/json

{
    "groupId": 8,
    "userId": 3,
    "membershipId": "member"
}

###
DELETE http://localhost:3001/groups/removeMember
Content-Type: application/json

{
    "groupId": 8,
    "userId": 3
}

###
GET http://localhost:3001/groups/all
Content-Type: application/json

###
GET http://localhost:3001/groups/8/members
Content-Type: application/json

###
DELETE http://localhost:3001/groups/delete/14
Content-Type: application/json

###
POST http://localhost:3001/favourites/toggle
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJ1c2VyRW1haWwiOiJ3b29uQHRlc3QuY29tIiwidXNlcm5hbWUiOiJXb29uIiwiaWF0IjoxNzMzMzk4MzM4LCJleHAiOjE3MzM0MDE5Mzh9.pLXjw-EiM8ypjGK22FPop-AJGi6APyMp8Nt_Ci7afls; refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJ1c2VyRW1haWwiOiJ3b29uQHRlc3QuY29tIiwidXNlcm5hbWUiOiJXb29uIiwiaWF0IjoxNzMzMzk4MzM4LCJleHAiOjE3MzQ2MDc5Mzh9.j7s45klc7mCMqbIv52f9JDEpcj7LP_FaVHb1aqgjNmY

{
    "movieId": 123,
    "movieName": "Inception"
}